### PR TITLE
fix: don't rely on buffer

### PR DESCRIPTION
**Pull request by ThaUnknown**

### CODE REVIEW

**Comment by ThaUnknown** [comment]
@voxpelli any chance this can be merged?

**Comment by voxpelli** [comment]
@ThaUnknown I'm no longer on a contract with Socket so any merging is out of my hands as my commit access then also is gone

Check with @feross

**Comment by ThaUnknown** [comment]
ah, sorry for the ping then

@bmeck hbu? to my knowledge feross is unreachable from 3rd parties, I've tried many times for different packages already

**Review by jimmywarting — APPROVED** [review]

**Review by bmeck — APPROVED** [review]

**Comment by ThaUnknown** [comment]
@bmeck sick, please don't forget to publish it to NPM

**Comment by bmeck** [comment]
@ThaUnknown this appears to be quite a breaking change so will have to do a bit more checking since it changes the types, but will get it out when I find time to double check impact and then a major bump.

**Comment by ThaUnknown** [comment]
it's not really major, it's backwards compatible with almost all versions of webtorrent

the tests fail because they check against buffer not uint8 so tape hangs because it's deepequal util is poorly written

**Comment by ThaUnknown** [comment]
other chunk stores return uint8 just fine:
https://github.com/mafintosh/memory-chunk-store/blob/master/index.js#L40

https://github.com/ThaUnknown/fsa-chunk-store/blob/master/index.js#L214

**Comment by bmeck** [comment]
@ThaUnknown it changes the type so people using any utilities from `Buffer` will be unable to use them after this change without converting to a Buffer.

**Comment by ThaUnknown** [comment]
then release as major, but no one outside of webtorrent uses chunk stores

**Comment by jimmywarting** [comment]
I think ppl should not be using `Buffer`

it's better to use TextEncoder/decoder(stream), DataView, Uint8Array instead. cuz it's better for cross compatible env who dose not have a global `Buffer` like in NodeJS and who dose not want to bring in another large dependency on a Buffer polyfill. all resent changes in NodeJS have become more acceptable of writing Uint8Arrays to the disk and responding with typed arrays instead. 

another thing i that i think is inherently bad is that they override the `.slice()` method. if copying is so bad then subarray should be used instead.

**Pull request merged**
